apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: churn-system
  labels:
    app: churn-streamlit
spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
  selector:
    app: churn-streamlit
